configs:
    #ENC[AES256_GCM,data:D2hXTeTG2A9eA+sQHoJrwBLOMMk4x9k=,iv:bBceuQEfzdHwTRvTBwwpfQo7NRTiC9e0AahnguInJR8=,tag:oKOKqyk4gqBXw3JuJBVaJg==,type:comment]
    #ENC[AES256_GCM,data:vZBtpTRWigepXlv9VKe2d1K6HjsEaw4t3znkfu+r3Hh40du5oqH6Wk1uFtLd39jgHAJkvG38tPVaf3gXueaEDouLfCfQW+bxTQ1jAAB0Gr2Kc5mySImBZMfFt0ec+Rqj7lbmKatuFt8KJHSjvaozEBExNSxE,iv:mGffATZC8ECNZXYbcTZcg4KQGwT3Dz5MqfB5dzvG+Qs=,tag:fh95EHzTvw3W4uKWP8jNhQ==,type:comment]
    secret:
        #ENC[AES256_GCM,data:gFjbgPYGBOH7lT9DWOvW+Oufukj/QrQguQKy/g==,iv:zaLBapmdn3vPlMe3fa5oz99j75YkpdT1dQT1e1ADcNs=,tag:eYI9rWit4zgrwYn3J3fgwQ==,type:comment]
        createSecret: ENC[AES256_GCM,data:pQu5zw==,iv:P3aITldM4HCKZtSyrkd6Ec0HEWeEKrVPMINUeq0oWtU=,tag:1gGK8B8C9HZA+a7tdM/oWQ==,type:bool]
        #ENC[AES256_GCM,data:rjtcjBbyCLfzt3yKcdncUfQIcfRahq2TXqvk4gqW4B88MlW32VR3,iv:CToGsx0r1QUnC4QybOiNRniElplC7iqlaF0v7rYnjtI=,tag:M60Dhld+mthV4NLTbNfutw==,type:comment]
        labels: {}
        #ENC[AES256_GCM,data:3+J5NSn+Zs22e41fmSkAEXfbfHwWBXtjyi/+SLS4jyj5fhe5plg2G277l8c=,iv:O3muxf5K8fBM3a/XYxqB90RxrH3DgusJtVSr9L8P2N4=,tag:GHt66w9QlfG2PhHwNa/YXw==,type:comment]
        annotations: {}
        #ENC[AES256_GCM,data:B5UOZj6xcPAltBZio7a2pKn3uFtRa+BnF5fB6d6O/yb8/hyRRbobvLiUDj//M5KLovZN75sHj5aRvQ==,iv:EOEg00q3Gg+3dg2bu1QnB70LCUd4/bu9prsB+X6JWZ0=,tag:+TNowlTUdKzGUFw0P+qONg==,type:comment]
        githubSecret: ""
        #ENC[AES256_GCM,data:ZOpKMMVjw488u/ydPGzQJWL3lAQ5Wg1CBT0Uvbl9wXM9Th354nd/3kmaoWDBzIlNgjQYhPkawCTUlA==,iv:dInoF4IH+IGiTSlY/0UGcoVzW8vX9nd7WnrBgxxjjFo=,tag:USKFqdNzizpMWtm3qF2wmA==,type:comment]
        gitlabSecret: ""
        #ENC[AES256_GCM,data:Nqn30u+QUntk9X5GTiITouE3e7o3i8Q7fqkiIkODkBdeJNSScBQ7muueBVzGwqehr7RZXxI5utE=,iv:WwwNSHLe6QoUvGMBOJb2vXqsmfb+XW8bbSoCENaP9bo=,tag:wkbhdINLN2XQdvC14gIElQ==,type:comment]
        gogsSecret: ""
        #ENC[AES256_GCM,data:dbCxAmvB13O1pEnI5VwySlNM5ckg3WpY4yhqutmgrs/06pcJNg2XjOkc0qVnCsFBPiE93gb/QA==,iv:Ff9u44z563kAXKDNkBRLZiqb+RnqGE3wrxfVf7P9Pu8=,tag:ZVTLWKfm2amnDIG/MCi2nw==,type:comment]
        #ENC[AES256_GCM,data:Q5CyZwpuZOGHdj+7ApUcTEIAQrvrJZh8AsjkkvDXwdawJgi2K01KWCom6ZuIglzl0bua3akmBueBPNYpiuLosX240nSRxXg9vyg3gpOu,iv:SMhnP2XZl4/uJNeT9GdBirMnlqHv/jBqfcIs/WienHc=,tag:qelcgShpftPsMki4eQBOfQ==,type:comment]
        #ENC[AES256_GCM,data:zHtWki1OMeR762GQPfwGekX4KOvHvS9aUP3MbbHWJPGQdC6jZ5Ia/KALE0rh7K3UsNBkM9RnbiWL8OLKERXwriz0nCg90lnQenBmWV2cAVc65uuXDLhS2ZUGnRU35cj0cF+oG2KhqwiWvR5xuU/zaozUovFtTg==,iv:XtA32xcCy/p3opMx9gSY1sYjCbTMswaWt41FF3VXh8E=,tag:eYlWdDqbREv6rdBTmWfL3g==,type:comment]
        #ENC[AES256_GCM,data:WaUw6I8FhD4SO9CyVPLDE5eTL1tuf1PZf0TlYyEIK26wg1jETU0yF1k=,iv:etnBr1tWcE+bOI6/NJDTEnBIfLWG33xvd1VDCw+a68Y=,tag:lrE822rO8yKjT9veeWjhXw==,type:comment]
        extra: {}
        #ENC[AES256_GCM,data:MMJjOKRUmqXD7X5yjXGYZ6HsvfHqeXhhZjLvpg==,iv:4R67iSR8T0e0LuW1KDAnEio58ADryn+av0s2077SSeg=,tag:MKaPIQ0Jydsi1EXBr3YPbQ==,type:comment]
        #ENC[AES256_GCM,data:qs0My5zzITCB9ouO5firNc7ZAEevKacelBy3AVFmqfk=,iv:lK4I/4eOE/XfPDFtCrdF3gvFo6RJ2TzHAZzoQYLjxzI=,tag:ZHTIO1Q2cyMZ5dJri3n1AA==,type:comment]
        #ENC[AES256_GCM,data:tdoGqxLCjhCMUrTIOQGXsM6Ha0n+aQLbXDHeSzyXw/VCTVHXuWapjYOmNgks9IUe4KW3i6qvAktYkit0dN78pcBH1aK3oFs56aCbRT9ra9OnDzTe3zen9CsjL2M=,iv:6XBcyU/GqZ7RaGAGkwmzbrLgZr6Rq9KvpZdKIADUOJA=,tag:/68St0livt/E22Cqq6pRJw==,type:comment]
        #ENC[AES256_GCM,data:3/aD5iqukWIyE4x972CPri8PG5Uv5lqynrAJe76fDTsYhpb4XHC2hhtYVUcGi5xKSw7bp5jOOUxXCtMRgAnn34T+Kg==,iv:YFxfYs87qkLugOCmN8VDuHO23+kiPKfgz+EaiT+LxUI=,tag:FMAxPMuTdGg38Zg5DzODfQ==,type:comment]
        #ENC[AES256_GCM,data:6U634LnEmGrmS6alnpJflYbHKQ4=,iv:vAdRBXikO5aun3VyO/3KS2Aq0glAgCQeMXGBGEVwz6I=,tag:UXxXNdYJnuAfvx16KTtEzQ==,type:comment]
        argocdServerAdminPassword: ENC[AES256_GCM,data:DDzqpKJmO3MR7BqW8007abidMLiHMrQ1uFk6pwhs/v7BX+HACAnxUj2diXTnjoxUi7QJnNizE6UtZtYu,iv:WLvkmB+6aO99tyKUNNnbX79OqwX8qv0BzxAbKUL/Fn4=,tag:209R4W6xYEo5rbL6DgORNg==,type:str]
        #ENC[AES256_GCM,data:hCyYznWVGlfFAVQUaIQHP+ngrl9HWtQ5uNyQqmdmjiQa09M817JiaZu3y650cW6DLEj+Vxm3a7Ux56HGx0eKhyBk,iv:3QHaz8aJ8Ck2WTiqalj5nQKi0wIEYZ6vGCTRmxtCPUo=,tag:2a70dQ+wzGtCPsLO0tXx7g==,type:comment]
        #ENC[AES256_GCM,data:e8/6OOntTgYhwlOUq+XxlDp3qp9wwBPjjYtjw4bWe22tq5I67HIEcusRikk=,iv:kRQzob0Qaj90xqo6F0KL8/RX1BXUjS5rO3EuSNpdP1w=,tag:1yoFLH4fVftrka2W8YLHMQ==,type:comment]
#ENC[AES256_GCM,data:0s+R/arckrKnSYiYd5HXyIkMfCSIHP93RKFXGTyi+pOzC9PJl1Q=,iv:+IQut5m+Jv6rKxkkEYyGy/Zrxw3Y6b7Opige42xXiDQ=,tag:4DBf+cG+j1AMBX1lpx3oJQ==,type:comment]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVEh6S3l6UytYN3g0T0dY
            ckQ2bGdlZXdrcThzeTRxV3hjbUNzVHk1V1JFCm1CQkZjMCtKaTY2Q3ZERFQ1OGpz
            c250a0hJajNXNzhVcERmWFVGMnBnWjAKLS0tIEh0a2RLZlo4b1FBVytteUxhSWVr
            V1dPY2wyQndWTmxPMDIwTEpsN2RnQTQKJqWNaaGN7K7MUal+fbN9zeVjAuEZqC63
            XEuyN7kkbY48w99gFuBCdQnvbKK2mY8nJqcikVegxsITxjdJLtFrNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T18:34:46Z"
    mac: ENC[AES256_GCM,data:fLO+fORW3YRBrl2qqDvpwXswb5DUeJMFkNENxpHRNEtVXLdYTHQUP/llXhJxRjtIYjDN+bqOkRRbxgtHpG4lLsX+VzaUFBNh3HOyEjAD61ZiAeyo4P6OIce+KZywrHZuZpW6BWPEMM5JimQFZCOmMmTN5BU56vHtx2h9jKfHMlQ=,iv:GHayIZkVLXCziSyG0qisX+Dvlqb4uHEP/AiX2TeJVT8=,tag:AVUveDcVDAkCeLvDrpCjGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
