configs:
    #ENC[AES256_GCM,data:Hlqq+vlP40n3Fl/eSjEahwUo5qJEGp8=,iv:N/wvzt0RZoGdkHzk7kTv7Cl2D489FEhK/m9qz9ozsLc=,tag:ltJRFIUPAQydbEq2XbP6WQ==,type:comment]
    #ENC[AES256_GCM,data:11GM74lh3GqPMDUQHHO9uBPDSEgFm/N3tWsFtcjQo0JwD8/3uRwWSx1HD3AYVxfTQ9DnR/fkOcn4WwKNAPodCQXkMteZkdW5139wJ/b/n67OoqXAqh+nFbjdKV5Z1gNe+yGhOsjaVNOFloExuMU88xgp1XNt,iv:5tWOHLh7SgVx4kP54EqX6++QlMttBEcJ8DeAxsIyO6o=,tag:dguTwSJjiw8ioN9ZZ767EA==,type:comment]
    secret:
        #ENC[AES256_GCM,data:parnTAGaRmJP1TCiuMIQWUUy4PTxfOYNKDTf2Q==,iv:xFPWQ8Z47OyNuGVkoYQD/LsXrGoM7xVSZlYV9MTe4HY=,tag:4+KbaQZWWycq+sK8Bw9MeQ==,type:comment]
        createSecret: ENC[AES256_GCM,data:Io9UWw==,iv:xTD3PL87krpDnIAKojHLmxYYJpYmJQXqsRJzt7w8hVs=,tag:Hunfu5BhhF8wiztbPi6f7w==,type:bool]
        #ENC[AES256_GCM,data:4vlFqjM+aB0aD3lWu/1VX/qqv9LvPbzQaX7m0SKGSlsSCC8OWtM1,iv:VWM+dOiXndMT4Cz0l3Bq2dNNwPQVXVkWs7GkRv2qP8E=,tag:oxtSJ1jS5dnBbLeTdXBqRg==,type:comment]
        labels: {}
        #ENC[AES256_GCM,data:R8YnRmDKkTs9/edQCS0klgRCe5Wugb1t6itmreHQwkiG1J5qoQ6ZWszn9d8=,iv:IKXfIp79mOt17AzCcuGNiTx35f2b1ZmWgmR/5ROA55k=,tag:vC/jS5tfg6AYbPXayM0ztg==,type:comment]
        annotations: {}
        #ENC[AES256_GCM,data:rhLCzMhzyjNod0s7myMICfLO3tx9mdO8JqgSs0P7WtUr24ZtrpuARRucuwwQUqYX2Y1TsD9K4++J0g==,iv:3B1Sr3AHfYY15ZGlgko0JE59xOYSSMS5P3ite/D6iDw=,tag:zaDUOo3Ne+/wOVslZlLSzg==,type:comment]
        githubSecret: ""
        #ENC[AES256_GCM,data:z+uveQUpWSl+7ryxOGRpLrZVnQsRGL42XyeottbsXF3KH2DuBN1LvXg3Lq9GZn75Rn6rBtXbqmFufg==,iv:jMNJn+Bn1HclDH1mRIgFyowB00fxzDi6fINUlsrp/iE=,tag:lI5KGWP9EEwYXBtSXTE9AQ==,type:comment]
        gitlabSecret: ""
        #ENC[AES256_GCM,data:c7FfPcLf3OU0yqKHOlnqnjsggYqqyUL6WQhcgCtRPmWtrSQ2/NYcMckbZj7T1y2aTjw+/TPSqP4=,iv:Nsoyn/jQBWlbTnpFAmLmZAAMpCVN36wwbvZ2GlUCU5I=,tag:SAAI1my90d4X6lkGNdjlfA==,type:comment]
        gogsSecret: ""
        #ENC[AES256_GCM,data:zfwgu1apBdKIqSSYBUKdfL/3ivYVCVnyIkCiHrbwAW7u8TtUrK4ik4y61R7vU1zCN/JualVSwA==,iv:T64z3MjfLbSmJ39Pou4h1+EYL+nijCt9TRthAZEc00s=,tag:fofUTl7tagwz7I3fIG4XfQ==,type:comment]
        #ENC[AES256_GCM,data:LgnxHo11mWtmSc5nimtZQNz6oCFRczSp+951e59YYkooOmoLh3OQ+9g9ozTWRGHZLUo6Hvt5X8c4I5aamzM9flUZLU3wjNcfe/54NGx2,iv:8d+a3+01CKi/MzdJMRjDikJSbnnEwNd9+TlrrgbF+A8=,tag:2OwyobCAJsM1+OQmn0RDnQ==,type:comment]
        #ENC[AES256_GCM,data:r/XZ2rMdd2m2mqKlvj4qSURo92Pyapr/GcKDxWFBqwgI0eKZe99sHwfJaEgBJZBooPIL9qHU3Vcfggcr1riFDFPBsM7cHx2idv6UUBebhm0IkmNg7YjUlpNhZg04kHdamVHNwpF1hl/3NRUBIg52HaX1fzVuJg==,iv:dfQ0IW/eui6N5ldt9DRUWi3ZjJh9gZPAw/RdnPM7ygc=,tag:UpCmOn9e4GAa/RLj4yrrCg==,type:comment]
        #ENC[AES256_GCM,data:0c5yT0T1Oth/Ht9N6HITjWczyk0NnrKxirSckGFfH8v3fVM98QAnXSk=,iv:7idnJkLZBepupt1rJ2HAjOuBHUGChlajNKOaHAe3M3c=,tag:xTsB0TKu6QuZwwyC/2I6ng==,type:comment]
        extra: {}
        #ENC[AES256_GCM,data:Oo2JyqL53SZXdZeBsCNo6p4wxoRHNsVIteykLw==,iv:jCzCWMeImMj6b0Xb1C4NJjdUOeJrw3u69QoFSL1v7mY=,tag:OQqmAnOeKAntCQE1jzJjkw==,type:comment]
        #ENC[AES256_GCM,data:fKL+25g+KwFEHOenqy5LCegGKlM0esLYT+SkfFLyTO4=,iv:pNBDqM/ImMuVAyhI4BGzAPC253YG/8vbKQDyovuEO8M=,tag:g6vTzHlOzuwcErAFoVmhgA==,type:comment]
        #ENC[AES256_GCM,data:Vw/mN4Fm97BciGQwjCrzqynkVO7b83saDg3miN1/+t3661KbfcXSNoNyrwTonEOi+uNyr99XEela/5jXqg3mjZm3+tGUK4rXrQ3OPRKiXk449w7G8kRS/HI6JGI=,iv:a38VdHqKN1ctAuESvJZgI4MWmkqrflK9i9YPi0gwDOc=,tag:uLnvj2Xf0NwSIoM/SgOKxQ==,type:comment]
        #ENC[AES256_GCM,data:CMvlw0qn46qT0R4LG6Wq4iXfZfdAowqMJDQ+LDQ7bu4jtOSFl9n/I9WwDOl7KcefKV1yHFVmV4fV8+9C9xVkmysDyQ==,iv:d3P2cIJlUtVHp6zxMEypb7jiaQ4o5GksFjX+U6tkKSM=,tag:O9BO78g+e5hUbudun+3Sqg==,type:comment]
        #ENC[AES256_GCM,data:i+5eg6u9wS6iqHk9pP9i7F7rvAw=,iv:W8+ABp+QsG9HcNmea4DEgnDYvs6iJu4uVpBiHkN5/lQ=,tag:sM2nQRkbcNPQ75jRqqyIEg==,type:comment]
        argocdServerAdminPassword: ENC[AES256_GCM,data:mo3vnQ4Zwh0VPQ7ERYNcE83sY1zfB+dUAmU8aBtDnRj7M5S9W/9uQTUErPcr0G4Xfqc5ISaKK6F0piKo,iv:Prr9PFcqCrrHiXOYf4Z5MNgPRDF9viJgiWI84BaeTnM=,tag:tJlKrDbya55OJV86F9DUNw==,type:str]
        #ENC[AES256_GCM,data:O70+aLV/1FczztkAAMRC09VM1DY6v1tWSck/jULCQon9eExc2JSIWAfOKPa565bw2UAfTgJUiPLEonM10bGSNFHL,iv:mYDVeu1UZHch0+ZbedgAXxe6TPhaWuw9jftJGNqwXQs=,tag:TKpO/1c0I65sd6LpHWsCzw==,type:comment]
        #ENC[AES256_GCM,data:3qbWaMw9pYMkcnd+vahkRbgF5K2IRIgLU1C0v2Y8KPrL25VCC1F+MX/bMHg=,iv:79ufJrg+CycvafmZOLGuWdflFHcp/rOqkphyy3vPE3s=,tag:eja1Tg8HU2SjZFe06yTRJQ==,type:comment]
        argocdServerAdminPasswordMtime: ENC[AES256_GCM,data:w48s72EIBWlSBPwIY8R1y3Ctf4k=,iv:VQcTALbeHKUkeGvVJARb6xmwaAeNwbMHxRax3FD8qj8=,tag:4K2W0yR4UssgOqwr3wVRog==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobmwvMnhwMVBvdXBONG1U
            bkthekthcGMrQVZDdjdKdFF0ejl3ZHhJbHpRCjdzN0x0YXVydWhOWTU3czFzYkJo
            eFJ0OW5YZW1mZXV3VFdWeWFZd3pMMmMKLS0tIGd3UzRFbTg0dUZuV1JScW1SNkJu
            MEt0UFFNL0FyOFZKWU82K2xBUENyWVUKKyzrMMluynJqKnju4h+5HcNx9r9kSl7o
            kvls+wbrl0eE6l9XmhfHwLu0u27w73VeoWdcapzkH72/dN0HWdjPAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T08:35:16Z"
    mac: ENC[AES256_GCM,data:i//7GC8oxazsd1KGBNjzOnT49YXdl5I5O7Xwy+jwOO9J9xgpImVosqIktIF5IOwe/V0ILuSEQ15+H/FHGyjcC9EO/vjC2xL6vjHv5IKFVZnp2rf2GEpJ3NJ84x9T9jZKaBY+DjQ6x5vSP1bGTOA/H0jM9xYbvBsk5DQxClORfYw=,iv:KTWEHeSWfmjEchpznsOA27nZtvWluYoEmWt98dSyHb8=,tag:xADj8FzLgWSg7/6HfmzNBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
