apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpu-device-plugin
spec:
  image: intel/intel-gpu-plugin:0.34.1
  logLevel: 4
  sharedDevNum: 1
  preferredAllocationPolicy: none