clusterIssuer:
    dnsZones:
        - ENC[AES256_GCM,data:T9Yg6JdM2vAmfsE=,iv:TynUxY487UDCM9OS3jNE/i+8xYe059z3Pa9dWzFLyCs=,tag:JNxz6Sk6UE1FkbeXO4cBYA==,type:str]
    email: ENC[AES256_GCM,data:SSLIyfNAsKYNeF9waDynUv6+SRckGdwo,iv:w4E2u47PBlYvaMFxbvgXuk8kqV9FXUy03TthxRXhsgA=,tag:iT0mXw57lN3T95JNFvTVog==,type:str]
    cloudflare:
        email: ENC[AES256_GCM,data:9XE1ec0ZmKwPNb2Y7kzQ5IS6aomxDgfc,iv:pp3VyMXAxi6UHftm+OkJNflGX+IrhtDBR+HzOzok4f4=,tag:3gLgCpdoNhypfBv1BS+8tA==,type:str]
certificate:
    commonName: ENC[AES256_GCM,data:RDP2FFT6sSVivfzIeQbDvglW6w==,iv:WL1dBhXZqYYvO3DtrESspXNn6Q9yO+ghQ7niFOL3Buo=,tag:L6kzTQVZfdaZoYlUPFYDYQ==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQmg3MlJXTmVnbWJlMGVG
            K3VFTVNjbGs5RHpaTEp5T2x0aURUUXVpLzNRCnN3bmM2Y2dBdVZqT1dhZEZMNVJM
            R1hZZlh5UDhjOGpCSWpFenMzQTBNdGcKLS0tICtxU3FpUDFUTytyTEFTNjgvbkFr
            azBUSWNHWmNBVWxSSHJZM010UDR2SzQKx0gPQckdUXRC1aKKLoTtKeqKt5J+DtC5
            5QLOwnRnL2/l6tFnX06O2GsJjaIofJX6X1Q4l1mOiIWdjehRAPBA3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T13:06:16Z"
    mac: ENC[AES256_GCM,data:lhdJgX9La+Et4FfNy5tcXkR7/bDNA5QjrNWvP672WOjWDsex41X1mWDtWBnnWsdHjnjjQETO1lTn9jhVbcgFsG4qHLNYwPgN7VsUdPbQ4h6Sdif3jj4f1awjwcFA6+eMCgjXnXHAtalWha61WrhjeEP4QdYb5Cjwn/zHaYHC8T0=,iv:v+iZM4HWP98CRhKX2B5pGMb9JRqO7M//TUzHPnrHnGU=,tag:AI0IQfCnvnwaXEsD3gKpPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
