clusterIssuer:
    dnsZones:
        - ENC[AES256_GCM,data:TIZZyzYoczP09Dw=,iv:57FpwObjB9EPi9lFTEms8fw5BfXUqInFfH7jw1aO7Zk=,tag:S/7xKbE7AgeEGE8c/jGrIA==,type:str]
    email: ENC[AES256_GCM,data:EDyBCmBCi3a8fOmlaais+tNOW7qZpiRr,iv:XW9YV/skoU+uViD0ORPTbclEp69GXi9lRyONo/YpgdY=,tag:7RsdONS6j1GzWLm9JfzVsA==,type:str]
    cloudflare:
        email: ENC[AES256_GCM,data:podoLVCNZWOMzZKUEcbHH3NRz8AvZG2Q,iv:WJhgQ1ESDoEmlFl3lCxMFpDHzpG0M/L8b+PycPM9J1A=,tag:F/jSCz/Gaf8K39anM7hSXg==,type:str]
certificate:
    commonName: ENC[AES256_GCM,data:Hdr8E4X90JlxVxZBMA==,iv:qh1sALnrBf4CA5RHa1rhkh+XSRBXdRskiYxjdWdZnjo=,tag:I8JYfh/EoKpPJgb53OL0VA==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYlJDY3ZYUWx2cGRadHlF
            YTRSTUZPeEFsN1ZidVpvVTZJbkhZd2F3c1Q4CnFNamRYNEtZb1ZGcmIxdU1vS2RU
            cVR5SitUWFp0WTZUWG5zcjdPU09pVGsKLS0tIGJLTGZuTTI4STBwMkFSY0NEZzBV
            WGdra0N2SWtWU3hYSm43bkExUFMrU0UKU1wUASuzvL6l4xtpZb2rGYWsW3+3k+nF
            S7F2eIM2HY35HCZt7aH+fIkO5UJgm9i8AxAa8Z5SdfKEC1RFs+9q7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T13:27:25Z"
    mac: ENC[AES256_GCM,data:dpTTUOY91FZ4O3gsEW8Dt7Ks1nW0Ts0YG/MqRu+E1DqhtbzUKz9l9j7cG1KYtMC5oNX7jtQUfApDj7dl30GQVz0C6IWRBjRP3AKPj1WsAuYcSa1tiYV/4sUrTfD+M/5zdjDGfbUMfCQMVfrGFJ1tue3BC926YcDvAhvNk9I9K2o=,iv:eXrJGZQDNqjJdAh6z5N5bS5N+AXtG7KhdAHSScKoaY8=,tag:SQYK5XXcS4etoyKn1pI3jg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
