clusterIssuer:
    dnsZones:
        - ENC[AES256_GCM,data:jALaZ26CV0a3SAY=,iv:r+weTK677HjIyI90Ny0L6hOvHJjxys6Fna3dlVXZnMM=,tag:p873XmYRUjj2xZ6Sxu5/mw==,type:str]
    email: ENC[AES256_GCM,data:wWmTGi1q+dbjoWIVhor/K//2LZ5FV76G,iv:CVpl0L7R8OxqgMR5KoPpkjo1sLSY78BHzZoLQT2zt+c=,tag:FqnfTr83OfdgpvNTzEwT4Q==,type:str]
    cloudflare:
        email: ENC[AES256_GCM,data:3vlT4IhW8S9TkFZAgc+yMVVdBh64yLq0,iv:XJn/iEHXhWnr8n0QBQDhztv1Rbohqh/cvYekK/yjcII=,tag:9p5KyIW3NgqWe+qEwIddjA==,type:str]
certificate:
    commonName: ENC[AES256_GCM,data:Y6QGwQbLrvy3KqBqLZzsi7rW,iv:DslvhhSK2FjYuGTDfkvQSydgySb7OnfSg35aZlhB36A=,tag:8Ndh7U+rNheqQT4mvrRHRg==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoK0ovMWZGMVo5NUs3aDN3
            ZWtHUmtZTG9LOUwxV1FPSlljdlU3QUFUcmh3CnJldXBlZkZuV3BjcFJRVVlEOG5H
            OERvYXZqN0Z4WEt3ZEJVTlU0Z0N6cDQKLS0tIFF6R21NczBZVkNCK0hLZzRpN0Jh
            VmNMNHozbElncXFMMFVxUFpHdFdZTU0KQbtj9RfrS8NQzUQhENoodkdXlN1oMTHI
            H0Oh5qPDM1DY0y3c/wHC5e/qVWPZWQtiyqR9Gij8U5RbgOo3n799cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T13:06:07Z"
    mac: ENC[AES256_GCM,data:JOhOGofhNAqSTYFOMHwtCqQIzNCGqpEYhm1x2h7kZLqcXFqwxRKDwEQh7mtBifNNx4P1tPLTR9vwYCfN7JnGapsczpvFg9ZGknHsJ6++z/GmUNwm6yZtybwiWx99gMrH3cCC/BL+5AJrqt0ZufeJEPlhlGolxUAvsg7/FYkqDr4=,iv:PeQZUoWaMCtgeuFvf7buzmwfZiTtjt0TGANaZDikgzA=,tag:ISupjp+dGBSEMK2/1bR7IQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
