configs:
    baseUrl: ENC[AES256_GCM,data:bBlloTGiXLDdC3i/O+0xIi0lmyCdLg==,iv:QsY3w95//NlyLRo/CNwFa/UmyVthV1nCf1aMjpg3zwk=,tag:EInxI6LGdEoqiTRqiQAbEg==,type:str]
    values:
        - ENC[AES256_GCM,data:5O+BEwXXjc8xcoQh6AGbAioVHvw=,iv:tMsKgsBF3lIn56Ewfx5XW5Orvyb2bioad6qK2rhEW8Q=,tag:QddJtIU4dC9pZfgiyv0u3w==,type:comment]
        - ENC[AES256_GCM,data:1l+vRKUVQg85218=,iv:ekyCygOWCQCuPwT55MRKW+kzjGghhhk10S/kE4IrKY8=,tag:5vE2oLxJWVq71r6apqW+Zg==,type:str]
        - ENC[AES256_GCM,data:UKNImkLSYo+tVw==,iv:B3UpQlekTaIo4D6FZ2NASjJL2rNLOUO0n1gjr+l0Au8=,tag:lCsEAVQXHAweN0NKDuKMew==,type:str]
        - ENC[AES256_GCM,data:LAunMIjrq24sNYN8ps3d17Z7Nw==,iv:JQwHwpyloSQSLIudpjbL9RuKoBClW8l91oYh/5suuU8=,tag:SpH63RGFxUz+6ObHzyo+eQ==,type:comment]
        - ENC[AES256_GCM,data:CfRRxIvyEQd0dYB3AN/kUHFZALwfPYQ=,iv:wDDqYWIF0A83K/7yyonoXOC7DpnzDq1OBT8J6PcHhGs=,tag:eHfnDFfxZ8DcyZbGYLYFxQ==,type:comment]
        - ENC[AES256_GCM,data:JZfDTm/P/qoI99xQUgPosQI70CNyLA==,iv:yQq5yQBAjvdMvzDf8f55tJd5ZhQY6n4Cp9G/h3hjwnE=,tag:m0C/KL9WikZwdngB2R7FNQ==,type:comment]
        - ENC[AES256_GCM,data:Smg443y7O6ngzUp7,iv:4HFONZlK55aGlqoRpqRnVsD2VquonOElHr3X5w5h6Pk=,tag:fHY5MjdpCXtn0ZdNXbB/4w==,type:str]
stash:
    token: ENC[AES256_GCM,data:QZ4Cc13sZqQ5tbpfwMqOeKZtT72xsy/BxI2RH2C36BC2h22QdRncpXzV4KsczL1BeC5r3K4BfckN+LAKWnHeMfJJuvJQDh244ymsUFcv7SO3yEnH+JLNrvWHnfdZJrVDdFmpcVYCcm54/Or1D/1ZtXmtOfn/DzpYBYdna0CYufhIGsSE5KwBtaHyDWQfN0un,iv:LDFyUTNWzNr+JNnOBzqEAmwzmpnRC3hB4BW/p0AE8MU=,tag:vCfooDL2VrqypzW9DdKS0Q==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR0YxVHVGMXV0Z1JOektz
            OVRDVTJKbzRnalE0ODBIZTduc2NlcGVaSkF3CmVxMW95NHZ2amlOQ3BPcVNPRG41
            VnNnZ2NRSmF4T011RVloclE0Nk5BNkUKLS0tIDlvaTdPQ1o5a3RRRjhPckNEOStZ
            NWM1ZWZmcXJZakp4RGVpYnVGS0s0U2cKsCqCW0YCuulvA/KSzLqDMq/DNZq+LhrV
            g7ruKAinK3Gjg+nuuSTOf79KUlS/WDYFFWbs8sD7erZCM2PXgjd12Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T17:59:58Z"
    mac: ENC[AES256_GCM,data:/43aS2My+8n1aimqlGGysdGd8DF/emmn6oOvbfxRuTYyuY2qrYcrF94gWAL4Z0k2g+cwWrMOlk73wq0ZDt1TLkuOBMjxzZAc0aU7lmnBPQ4Lea2le7S7JaT+Xp8KMQn9scdgNKo0rMGoMseALX3zYBqLHEQ9nsklQjuR5wIBbx0=,iv:7T8MEjhxs7tdCNtPI/ftrN8AaJxRuA4PxImuhtpNu8U=,tag:Ko237NhibzQhtzBxQz+2Bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
