configs:
    baseUrl: ENC[AES256_GCM,data:hnojyFR6Eagp5tBChl10jgi0jeLnig==,iv:7X7leVLZ/mc7WZt9nuLex6mc3KXlIx7YuL8+UXBmxAU=,tag:w+QTchES3DsV6/p6DODn/g==,type:str]
    values:
        - ENC[AES256_GCM,data:gI90VdjnE6FOwJdn1LeaphKMUGQ=,iv:EZsindedBJMqG5EO7Lcf8/viuSE7BR1gFHwf3TvDSJI=,tag:NiDpvy+J9lFpvFboMuw9MA==,type:comment]
        - ENC[AES256_GCM,data:n/QQwTt6uuAOdOs=,iv:y1bMNRU694/Q68XJ4dXZGietfRufuO9YSUfzbvoLrn8=,tag:m8O3j2ujnBr3E9OWh/gTYQ==,type:str]
        - ENC[AES256_GCM,data:MGVqtLkW5K6GQg==,iv:y6+oZYztBwOQR9UNad2cmCGpfSmWC9Ih6jMKd+sdfCU=,tag:4LicGyGkh518QEfHba+EvA==,type:str]
        - ENC[AES256_GCM,data:XorEE4VzP5d5Pwp1/H15mgOG3A==,iv:0F34Qhci0ECyPfdnb/jwPlD9YWunY3fd+eL7WpmYKlc=,tag:HEl7bcgydwILPfLeGwA/Lg==,type:comment]
        - ENC[AES256_GCM,data:ixwpBpX4I5j5gYIad1PmPVAgYsNZxpI=,iv:iHNy8fi+V5W13lwWmE5PjH6D0ZLUQiCt+2VSf+VGqzU=,tag:lW2x4fuGqe0x79WYKOW3Ug==,type:comment]
        - ENC[AES256_GCM,data:HSvGL53sfmGfdqDgiADt5uG2BVPrJg==,iv:2aGozoQtEssInj+GI/P02ddKBUbg4TBz+fKSon82fYk=,tag:Gpy3xjXYcisT0MZbLjuADA==,type:comment]
        - ENC[AES256_GCM,data:e4rlA/F8XXrWRxAR,iv:7TheJFnjvm7lCspYYZRm1WLNxverZB6OuJGYgQDaeZ8=,tag:HgZcHcF65nPZrE2R8P1bgw==,type:str]
        - ENC[AES256_GCM,data:07hLtLxyAL9ONJ5Q,iv:9NAn0m/VckX01SYEP8FgG5BtDvgvwWlGeUbM6REXC4c=,tag:s6dLMojIprtPzzz37maW4Q==,type:str]
stash:
    token: ENC[AES256_GCM,data:YWWw2UkhU41+3/2VZLf1OCiJ7lPhYGRnWPDDWIBPY9axnsMZ1tFVP/r6OpFuDB2Oc9eGKpTqsCKu9xCbNpcSARbQeMQXek7fspAwD7VxDl/7cee3/KtF4Kyy8V59+czvAwruzKu7N8HmKNSSMeqehZgeoU2eOd8SHGz3PMYGVUmVYG6Lvjg+RDI/E3EcwZq7,iv:wRlMiQEWBBX/YuVP7Fi5M7GWVByZT4pCnR+xcRyhglk=,tag:xHqrbS8QaMdAFunSZ+K2Og==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINUxyUEU0OWlzbk9OQ0sy
            ZlprS0MzK0dIcGpXSitzcTh2MDQ3WVFXUGo0CnA0RkFOMWptc2U1OFJja0tmSDJr
            L044d3RvVmQySEJBcWp1L1BqTTV0UHcKLS0tIElobUs0ZHBYU2d2TDhXYVZyWm9m
            ckVkL281NWZtb0V0M1N3WFEzZ2c4WmsKLuwWT4QQ0a9yNbvxILQayeIkCUGf43ha
            UiCzHtDFt4V7uixHObQAQArue7NrXpjJWADqKOla9oyEkwPlqqOhMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T07:55:19Z"
    mac: ENC[AES256_GCM,data:DC27jUKermPoRCE9bFg+gkm2lGOcyoMZIJIfzOHNT8WqA5PIz1iGwKZ9+l58f8FohZyTf91hvmSjJctSMepqy7IYH9HygKEdcUMfO9ETmUg5fZf+9WwkGQVlF4ToF3zqIBvjrmZJxe4TbtIPltgbgl7ik/9+90xJYmt5IExSQ1Q=,iv:3qX/mnmpG+yzlAVeWdNkKO/Lyh07wVDkQoIBadMA/98=,tag:FXnE6KCYAYckcN0lmx+4UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
