configs:
    baseUrl: ENC[AES256_GCM,data:6R8IyEuz/hLZkkEv3x4yzBg6oItdaw==,iv:di3gaG3jc2O46Ye+sykhhrcIn5Ret/bCJzYJPw8La+s=,tag:fWVzou3YZRPGtCfSjRIm4Q==,type:str]
    values:
        - ENC[AES256_GCM,data:fZ1/L9xxHECTqiu4vV1pDVpcPic=,iv:4NmEpd/1FoZMeWbWO5WPD24hKDZ1YJWjwfxwUlpIuz8=,tag:kVW+Q30foSgjHYnH+SQ1og==,type:comment]
        - ENC[AES256_GCM,data:2PwBDnZO6BS4KzM=,iv:H1hID2KUqfC28uRpIv/q/zMwLvYo5Xutxt3pF6r1bs0=,tag:x1l53/p8Ylvj2DCQegnazA==,type:str]
        - ENC[AES256_GCM,data:r1zykHibU3vuhA==,iv:PyaIesHWiPPoYpbS9sM7Q7zKtRmfSF0VZ9nM5iBG5XA=,tag:DMCvwHayFnirw4n1wx3jFA==,type:str]
        - ENC[AES256_GCM,data:OpRGqeEkc6CvAAbJu4Z61nN5yw==,iv:dux3fQYyf7JtWxI2XpaUryAqR7rqeANNJukhKx0aVH0=,tag:k6XsE4sonSiPntlTttUeIw==,type:comment]
        - ENC[AES256_GCM,data:TVIZc8W+v7vWQmEuFxcGWqqrvsYDhlQ=,iv:yvfF4+Pxc0obUpaGYtdjjkoXJubvH5ncWB5jJv1SuaI=,tag:cW7J23BjGGII3mFVyKuDQw==,type:comment]
        - ENC[AES256_GCM,data:IutbOZxi3uaciLyhfOrszspWZBvLBg==,iv:OO+yUU4Bx+v1FQn1bQNY0svU+TwywjikQ0yhrbtkXz0=,tag:8Qtw33EzzXPMrABuMBg9iA==,type:comment]
        - ENC[AES256_GCM,data:xzxDx20ugkWNOWka,iv:1JHFFsQjLg4W2TnA8fs2EAI2aAX7hCO/FD1x9cxgU8s=,tag:XMY56pTxkZUWYanc58vdRg==,type:str]
        - ENC[AES256_GCM,data:rdb+6Ey0JpycZD7R,iv:OSgpFoF62TLS1ZyJsc5t6ml2+k2olpqW/eqFs6gIpYg=,tag:XHX7Mr5wJtkmegWpj9VIUw==,type:str]
        - ENC[AES256_GCM,data:HwFgPiGagcBV,iv:o9OJN1aTB6LfZ2qZUP+c+Ht3zCkZtI4pdSirgIzxHYE=,tag:WiYHt6+VdC/muEoglaS3Sg==,type:str]
        - ENC[AES256_GCM,data:mm62xupZvtAOXJtX0Q==,iv:PGqK+zcvuAwieCroitB2ts5vADOeOgMdlNKtiixCX0Y=,tag:iclXrkKG5BRtnLM5Z3pbzQ==,type:str]
        - ENC[AES256_GCM,data:PklSV7q+2A==,iv:qaCIuf6lxx8NKUdYfOs00Y9uORc5Q/gbYmrUZvVqKJU=,tag:dsbjePMt7+qwPARcPgyEmA==,type:str]
        - ENC[AES256_GCM,data:zLCtZ/0=,iv:o3RvZMrUVcESPAJxaSw98R8RnjKgFm5icTEbv718KAo=,tag:YCp9xWuQu5jxy/lFm8qi5w==,type:str]
stash:
    token: ENC[AES256_GCM,data:H/hV1xkTUx0DQLIYhUmzMLs92RZebjWT0C8ewNrLCHqMsYq7fNneOtwuMXOG/t4qK0bsTD6dKl79X09lPNystpry6hnpDBcoqcVFuyc/oX9dpnFuHTgIcxTyfUy4XF0IPuJX6rOKSy25gl9oCHeWvMZXaKyK6MPBadLH37bulsb2O7C302VWW/tpU+cZCXwA,iv:nyTGYn2bIZYlDbOms+OHZuV+7TWhBRzd0jYtY4cb1vI=,tag:yLxN13fDNsoaNlXi25Ptfw==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M0xMdlpocVI0dndHZ1o2
            NHdhWGNMV0dRYlE4dnJ5NXJWMGcwalcwbEFNCndvWDFIYnJiWlZCM1BDK0dxZ3pm
            WWZVck0vZGhiUUtaeDB3cW5rUG5NVUUKLS0tIDFkYUttdFNNRUdOZG1pK2g4YnR3
            RXpMSUEzSytEL1lEWXNXRE5GK052MU0KLX+YLvTyT9n70I3rcmk7bOpZD4/aiI06
            +RB8rRDnifkYbJ54l4DsMmN6wsmyP6HE1dtHFMqBC7GQ3YgmgvG72Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T22:03:56Z"
    mac: ENC[AES256_GCM,data:lDyJuFD7wkOhR0C4UJC2lpoHHhrlXdTiB5lxWnF+o/kqHmFlF0S2KF0dVzqhJmr4BHeSk4mbB1WuOyMccr3HYbONjhvNC4YeZ6ZwEatFp9ixPSqOqIs90IRPL/fWZiMTZ1xCjSTI+ritJGEp1u+fTvva3aLnwyz7PQAlgmGcPDE=,iv:LrRysfoPqBs9Y78Ngu2/XpSb72OirvtOGVpBYylwYnI=,tag:FHbI8BwHfg3EcIdacrCpHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
