configs:
    baseUrl: ENC[AES256_GCM,data:IkzPsP2vDo1tRTIVj4fD351Zp1lbeQ==,iv:0XMOG37A8kS9ycPCDwSLj5M6VS+nG1dm65jPNkrBB5Q=,tag:/apho/P/6lbMkYkQun1adQ==,type:str]
    values:
        - ENC[AES256_GCM,data:fDVEOROqzyV6LVVR2Out7HkU3F0=,iv:AgVhIsjusDUD6v7YzrbaCGH0eTtqMpBWdMT1olhKl5Q=,tag:5rMGn0xj+xSHMPvlnSy7Eg==,type:comment]
        - ENC[AES256_GCM,data:DEyx5RtWS5AUEZU=,iv:InVMuudcfwXAXX5zAoeio3JpntiGFJn+wym/9Yqv17o=,tag:vp4Jg3790/oBYE9yRqyk+A==,type:str]
        - ENC[AES256_GCM,data:7OJonI37dkoPSA==,iv:HK8Nk2n9gUtb8FNv3ubLezSDY/13U336Azih4JkyLEs=,tag:iorsL3BYEVg2iE77iRRG1w==,type:str]
        - ENC[AES256_GCM,data:JVTbEVNKa92PM4G+32lo+WsHSg==,iv:8z7JeB03kDeUy3MWn8ZA6HxoqH7azuBp1HsGIdvzXb0=,tag:U5sPBd0LD72Hjwn3yLCEug==,type:comment]
        - ENC[AES256_GCM,data:D8YPQFlP0dBvD2qUNImVp7VrRjYNhUM=,iv:0ZrvHip0Rj0AfIMrghKyy5csMJO5EucOc4XLIEaYLmc=,tag:r5/41SdkTUB3k2u5HOXBbA==,type:comment]
        - ENC[AES256_GCM,data:FXrQniP3Fd+iXlnxMS6k2ygJ9mEWfg==,iv:f20d7fAHA7TGFDkS2EEQgHxnFkT7uHO/oYocDKaTVPI=,tag:vvpIs+qBY20Ta3r7J9xSLw==,type:comment]
        - ENC[AES256_GCM,data:48kj0kNUAft0//KQ,iv:jepJutzyLLrTGaOEe87FNn7Ci2+XSsFzOjE6w3N5ozc=,tag:NRUKl/iobGAlxbVlcWIi9g==,type:str]
        - ENC[AES256_GCM,data:krS/WQsrY7nVTbn1,iv:1Z41TpbJ2hI6l3a6/qLBg3p4rf2HmWmAm0vwy57AujY=,tag:azSnBor8C7f5aItqSUNdJw==,type:str]
        - ENC[AES256_GCM,data:528jEzmCynap,iv:6DZSmoiui+oLdYDrhS6cbBi5UlhCU0uo1SiauGE3tSM=,tag:9YAfdrpEvhuoshxTyLVcrw==,type:str]
        - ENC[AES256_GCM,data:gtcn7HbCd/U=,iv:4+zaDI/dvo3xPyNUz+eqyv6y1D6zbjc83G+oaAga5kE=,tag:1kzVt4qGI3FJ3D+05S41Bg==,type:str]
stash:
    token: ENC[AES256_GCM,data:kvcchI3yMTPf7+yfu5bkEILrIG2Zzaf5Bie8F2ONsjetD7Tgom6r6lRHMB0JQlBRfpZfw9bAEKzHKEj7xuqKMd+vh2z0y8vTcXW/T+tkHizaowGNI935sTDAXg6RRYq1MGApR8lwxBrDReP/u0SXMt1TYQprS7M80rYIjYQf+urMMsfxsK826SJwDyfqogg/,iv:G2f0DWpFcMmjUmli8bUmyJp0NxCPpBWQd90148lkYZ8=,tag:0n6FZaArepKMCbm9QK+Vgw==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaURwaExvR2pRcm40Y0s1
            OTFmWFU4eGl6aW03RDN1Zzc2L2VQVzhXRldzCjR6dTc5U3dMVU1TVFF0d0pRSCtV
            MDZEL2JMM0lyVTFOWHcrNTlWcXNtMDgKLS0tIFdIN29TUGFybEQ4OEZONzdhRHlO
            YVdSTjkydzJFcjY4VTF2cTRycnlBSXcKckz5z+vQrHdtRYfGFTz15Q5qD1ni/tuq
            HcK1V8gVYPHFEIDTYdQdArnmNSxZg4B2oSpSUU+2bUQfDLWYbxkccw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T06:23:09Z"
    mac: ENC[AES256_GCM,data:m7Vej4qLPhR0vWWmF6pPDFqwdOAuWJ3571G1cAaoF3lo8pF5toEa+HAw55aII8P+R7s/bsu+XZ5qqDg9R4B9RsAml25HHXYtlJ+1zDLSZ/hruTuq8wP4LMCC5m+8gCgquykexwZRMb3h2U6Jy935GcuQJxYk2BGPp0lBoqoUwVA=,iv:sbepyBf616p34Yd0gWED7tJvh6CIhHU9s5VfzL72OpE=,tag:faZmM14KnegTCr/QWg3HKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
