image:
  repository: jauderho/yt-dlp
  tag: 2026.02.04

persistence:
  storageClaimName: stash-media
  subPath: media

configs:
  schedule: "*/1 * * * *"
  activeDeadlineSeconds: 1800
  terminationGracePeriodSeconds: 300

