controllers:
  komga:
#    initContainers:
#      init:
#        securityContext:
#          runAsNonRoot: false
#          runAsUser: 0
#          runAsGroup: 0
#          allowPrivilegeEscalation: true
#        command: ["sh", "-c", "chmod 777 /config"]
#        image:
#          repository: alpine
#          tag: latest
    containers:
      app:
        image:
          repository: gotson/komga
          tag: 1.24.1
        env:
          TZ: Europe/Amsterdam
          USER: 1000
        ports:
          - name: http
            containerPort: &komgaPort 25600
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
#    fsGroup: 568
#    fsGroupChangePolicy: OnRootMismatch
#    supplementalGroups: [44, 10000]
    seccompProfile: { type: RuntimeDefault }
service:
  app:
    controller: komga
    ports:
      http:
        port: *komgaPort

persistence:
  config:
#    existingClaim: komga-config
    size: 2Gi
    storageClass: longhorn
    retain: true
    accessMode: ReadWriteOnce
    globalMounts:
      - path: "/config"
  tmp:
    type: emptyDir
  media:
    size: 1Ti
    storageClass: secondary
    retain: true
    accessMode: ReadWriteMany
    globalMounts:
      - path: /data
        subPath: media
        readOnly: false

starHostSuffix: &starHostSuffix "*.local.naguiar.dev"
hostSuffix: &hostSuffix "local.naguiar.dev"

rawResources:
  middleware:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    nameOverride: default-headers
    spec:
      spec:
        headers:
          browserXssFilter: true
          contentTypeNosniff: true
          forceSTSHeader: true
          stsIncludeSubdomains: true
          stsPreload: true
          stsSeconds: 15552000
          referrerPolicy: no-referrer
          contentSecurityPolicy: "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; frame-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-ancestors 'self'; base-uri 'self'; form-action 'self';"
          customFrameOptionsValue: SAMEORIGIN
          customRequestHeaders:
            X-Forwarded-Proto: https
  ingress-route:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.1.200
      kubernetes.io/ingress.class: traefik-external
    spec:
      spec:
        entryPoints:
          - websecure
        routes:
          - match: Host(`komga.local.naguiar.dev`) || Host(`komga.naguiar.dev`)
            kind: Rule
#            middlewares:
#              - name: komga-default-headers
            services:
              - name: komga
                port: *komgaPort
        tls:
          secretName: certificate-tls
