apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - affine.yaml
  - argo-cd.yaml
  - cert-manager.yaml
  - cloudflare-tunnel.yaml
  - database.yaml
  - home-assistant.yaml
  - intel-plugins.yaml
  - longhorn-storage.yaml
  - media-flix.yaml
  - n8n.yaml
  - networking.yaml
  - nfs-storage.yaml
  - pihole-dns.yaml
  - reflector.yaml
  - stash.yaml
  - telemetry.yaml
  - tinfoil-switch.yaml
  - traefik.yaml
  - victoriametrics.yaml
  - volume-snapshot.yaml
