repositories:
- name: emberstack
  url: https://emberstack.github.io/helm-charts

---
releases:
  - name: reflector
    namespace: reflector-system
    chart: emberstack/reflector
    version: 9.1.38
    values:
      - ./reflector.values.yaml