grafana:
    adminPassword: ENC[AES256_GCM,data:Qluz0KD2mcn6hQCy,iv:NHUOtiR7XkvmdTp5pFxowUOKlO2n58T4jZVUrKGobao=,tag:c8LM6RA2iFZwEasCTc1iiw==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUjZwcmc1SFA0aWg5OFcv
            QjhNcnU4RDZ5amZmbXpZU0tNRWRRdUlUa0ZjCmRRaEQzdnJkejBReUdRYlRSWnZP
            UWR6SU5COUV1elFNakdZTUVZbWY2MlUKLS0tIEsxaUF0QUdTcCtmUENXUmlqY2tW
            aVk4WWV2dUZmYmJzdnRyaUhodnFtcGMKjMlygPnD0ataaN1nG5vN0KLpDXjpa7yw
            MukGTyKnqBegnAhygTVMYzcIVQx2sUX+eMXe27i/ix9a6qTY3411KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T08:01:17Z"
    mac: ENC[AES256_GCM,data:X4GVv5Ucy8ejfvGSxdPCDWzfyPlqJvNJWBFEUQ/eUGiQLzkph/Ud9c/aWKBI93exRZcxoPcKRkYSrnxRbsV0GYAXPz5QGXxLT7vsbOpnXTLmJdC4L6Jow8bQj5XmmPOMX5iRUYJQFZUwBfVntHfTNCArqg/9ZlBGFiOrMySRPuI=,iv:1lDoX6KYHaNqFGZbKD3T/uY5CNmr7CVOZnpjCch6tWQ=,tag:hB5GZL6Bib4TQ/2602JQXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
