grafana:
    adminPassword: ENC[AES256_GCM,data:ktPfdu2vX63xkak3,iv:tdhY1Du0MwB2Vs4CgLGtNziAP1Dj+TlINedFDpUIFlA=,tag:+t0r9vbJpHZjKy0vR6iDeQ==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR00zUEZKWUp2YjgrNEsw
            dFFxOWREbHYzQVh4SThKTzltKzA0RDE4OXhZCmphbHVqbmE5bm1pRFh4OTV6VkRu
            T0RGaDkrVDlaWG1zOWRkdnZtM1RFUmcKLS0tIHJZanI1K0dBMGVIWWxaK1dhNWRu
            M3YxV2hhbXpKelpjN0FxS09Pb2xzQzAKdGKH9NEm+QNWPzukWNKUplN7RVUHEK/L
            wfpDncPt+6QQ39P8HL9e3FkZx5ZJFR1M6LTiQNvo1AgY4RqjIVlIBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T06:15:09Z"
    mac: ENC[AES256_GCM,data:mE8w5UsQtf1T0ZUwEDf9j1T1ADt/tqQKXRVNBGoM9zdqfa426g4gvMAVN3kXds63HSEA5eL6UAGOCRzSnSH72tvFu/5WWriv9vc6qH189b2cZRg2gdmqWV1lAUQFkHe7svR3l4Aa6FsL3C8WY/qkhD4fBawGrcc1mgSQdqkYhbE=,iv:y6eRQui3qo0YuXAVFhIgx67d20jZNbnyllhzbHdAsZ4=,tag:WemwyMKQjyMtcLYAafsJeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
