apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ds412-endpoint
  labels:
    kubernetes.io/service-name: ds412-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 5000
endpoints:
  - addresses:
      - "192.168.1.110"
    conditions:
      ready: true