apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ds412-ingressroute
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.200
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ds412.local.naguiar.dev`) || Host(`ds412.naguiar.dev`)
      kind: Rule
      middlewares:
        - name: ds412-default-headers
      services:
        - name: ds412-service
          port: 80
  tls:
    secretName: certificate-tls
