repositories:
  - name: cloudnative-pg
    url: https://cloudnative-pg.io/charts/


---
releases:
  - name: cloudnative-pg
    namespace: cloudnative-pg
    chart: cloudnative-pg/cloudnative-pg
    version: 0.27.0
    values:
      - ./values/pg.values.yaml

  - name: postgres-db
    namespace: cloudnative-pg
    chart: ./postgres-cluster

  # - name: postgres-backup
  #   namespace: cloudnative-pg
  #   chart: ./backup-restore