repositories:
  - name: argo
    oci: true
    url: ghcr.io/argoproj/argo-helm

apiVersions:
  - monitoring.coreos.com/v1

releases:
  - name: argocd
    chart: argo/argo-cd
    version: 9.1.7
    namespace: argocd
    secrets:
      - ./secrets/argo.values.secret.yaml
    values:
      - ./values/argocd.values.yaml

  - name: argo-ingress
    namespace: argocd
    chart: ./kustomize
