#ENC[AES256_GCM,data:mjgLxdjdVXCqQY/9o+NubW6KDz3iC8VNYgu7LsLbpD8GUQCQwJSxzfespnoVkYCjCk9g756EtiaKZ44fNKteAyzOYboEW7a+,iv:IoTqnPUR5dPxmbbts1B8l9MRld7mRYL9MMJxn/1tCH4=,tag:Nd91orVvmhpTNw3NaMhvfQ==,type:comment]
adminPassword: ENC[AES256_GCM,data:G9eUGYSmgRYusHyD,iv:hcjnWh64ZBRCQpPnDQAgoyU5GkFDCzvPHK6EGVmsCSA=,tag:1UGY45HuxstyOlaolR0Xdg==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybnJXYUZXYjg4aHU2R2ha
            c0dGNjV5bWlHU0xvRk9FaE00Nm5QRHNZbkY4CkJEVnd2WW5wNlkyYXcwUEdYeUlK
            dUlaenBRUzk5SHhhOEp3bk9oY2FxdjQKLS0tIFV4ajFLV3drV0NjRXQzOUhyWExv
            YmlEOVl0ZEk5clhWVWM4UFJrMVIzTlEK39xwDSKzpYXMZWhWl1tUL+puQSbHtmxN
            iS8sq1X6gV1zXfUpwfXjpU40UrgyqBcVxKylaJENZLnQi9HgIjKZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:22:41Z"
    mac: ENC[AES256_GCM,data:X2RqhgUEXoGzZ32Y5XPmtkpDQ7DMLTDGG1vQd5HkxN0V4SwlafrKLVRNBfw45rP+F9qQ7QWgQIphHCzFITSQ8MTYepcorW2V72WmbI60Q8h89FePJVZcxY6SKMnLuBi4gYtON6esfmwjpw9NgHSOffVbG+QL+r3FFI6YC3AbUrA=,iv:aJvbfgYFnZuc8U/Rg80Qvr3n9CsNqQSkqyXgaajK8M0=,tag:wxpSfM3zDp3egREdrNFyEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
