rawResources:
    db-secret:
        enabled: ENC[AES256_GCM,data:yrsrbg==,iv:7T4KDDrklXAZH4ehDTC1h28YC0YD1Af0zAfhKr3MLd8=,tag:38dJgZVi7LO5LkM3T1vwuw==,type:bool]
        apiVersion: ENC[AES256_GCM,data:QAM=,iv:0/fWaEa2a1xa+ImM8G31TGMLg/U4jocMrCi7WuxDsgo=,tag:XqSZi2IlWuONsHxPQvMNsA==,type:str]
        kind: ENC[AES256_GCM,data:B5l67a/i,iv:1HpDb6+wcVZUQ83G6gI5R0NsN7vMPmlmWcdaexzZLZY=,tag:Fjilh/q/7wmlGDHmNJRRcQ==,type:str]
        spec:
            stringData:
                password: ENC[AES256_GCM,data:9S02uJU/CQYwDWSEvQtjCQ2Pcfg=,iv:2TL7xWbfspPV/7vHf6FG8U3pcssJb5/0udjHn4SKZ5w=,tag:YSsHhHeLzJCU2Yxhj3Mp9Q==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SnFKK2dTWHdGbzI5KzY3
            WjJxRVB4WUpPSXZwN1prM2VVODJoYlhwc2s4ClVLSXBFUUJ1UCtmN2VKcHJibDhy
            dEpicFAxNU90RjVEVlU3U0ZlUEhXVWcKLS0tIHE4Z04zLzVMYnJaZ2Q4M0pHUElR
            dTRSdFRJMEFQOEtWVk9VVmIwcEdITlUKVaW3vGx4MdZrgsg02kdIjP+advQNJcGL
            Ur5XMHFc9kBRdg0kNv4NC5qn86LEZGTf05+1ZWtCGVG7XbqjdPfeqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T17:33:14Z"
    mac: ENC[AES256_GCM,data:+WiC4R2EaWVcrrS07rsiYt1QoQ1nv6P7CbDX0K+zE2dvsXzCd/19UmWV+UJeCLFDV6LrFqsaiCB8VjA/A/xGFG4Wex5FbOu+qhYn5KlDc0iKMGQL9XovlSi9OohW88XF/9kTXuTM9l7XOKzZQSWJtySTGjbcKhevIE4A1Staxd4=,iv:ff4Ct4sSdGEZJio1VSXs5nNkPF3FLtVmbKjzYabvjxc=,tag:vKHpUEEe+sidJBo8+2wIPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
