repositories:
  - name: vm
    url: https://victoriametrics.github.io/helm-charts/

releases:
  - name: victoria-metrics         # The name of the release
    namespace: monitoring   # The namespace to install into
    chart: vm/victoria-metrics-k8s-stack
    version: 0.39.0         # Use a specific version! Check ArtifactHub for the latest
    values:
      - ./values.yaml
    secrets:
      - ./secrets/vm.values.secret.yaml
#
#  - name: victoria-metrics-ingress
#    namespace: monitoring
#    chart: ./kustomize