---
repositories:
  - name: community-charts
    url: https://community-charts.github.io/helm-charts

---

releases:
  - name: n8n
    namespace: n8n
    chart: community-charts/n8n
    version: 1.16.14
    secrets:
      - ./secrets/n8n.values.secrets.yaml
    values:
      - ./values/n8n.values.yaml


  - name: n8n-ingress
    namespace: n8n
    chart: ./kustomize
