apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-ingress.yaml
  - grafana-ingress.yaml
  - vm-ingress.yaml
  - vmagent-ingress.yaml
  - vmsingle-ingress.yaml


