apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: victoriametrics
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.200
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`victoriametrics.local.naguiar.dev`)
      kind: Rule
      services:
        - name: victoria-metrics-kube-state-metrics
          port: 8080
  tls:
    secretName: certificate-tls