apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vmagent
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.200
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vmagent.local.naguiar.dev`)
      kind: Rule
      services:
        - name: vmagent-vm-victoria-metrics-k8s-stack
          port: 8429
  tls:
    secretName: certificate-tls
