apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmfile
    spec:
      init:
        command: [sh, -c]
        args:
          - |
            if [ -f .sops.yaml ]; then
              export SOPS_AGE_KEY_FILE=/home/argocd/.config/sops/age/keys.txt
            fi
            # Uncomment line below in case a plugin has been updated an it's failing to install it
            # helm plugin uninstall $(helm plugin list -q)
            helm repo update
            helmfile init --force
      generate:
        command: [sh, -c]
        args:
          - |
            if [ -f .sops.yaml ]; then
              export SOPS_AGE_KEY_FILE=/home/argocd/.config/sops/age/keys.txt
            fi
            helmfile template --include-crds
      discover:
        fileName: "helmfile.yaml"
