configs:
    baseUrl: ENC[AES256_GCM,data:iYaSA/KeAHK7zw69jo58KpufmL4PGg==,iv:grEGXk45P5rfoMIepKsXxd4bxYc/pVpAyFOR+sbPyD8=,tag:wfq1zLnwkOyIIXNTYk14bQ==,type:str]
    values:
        - ENC[AES256_GCM,data:Rqc7VfO90lJy/Jg=,iv:WCGycXkRzpBhkYfJ/kTCwNF8WZG5tHQaC8ZoK6dyS64=,tag:q4tSP8/sijoKfjOnv2mdqg==,type:str]
        - ENC[AES256_GCM,data:EqMVRS0i16bxPV0J,iv:3bVETWqQTIIus7LkroSAvJ+jqYiqEvUmduW0M796flQ=,tag:VCo37P1sSQtiymqz0DZvFA==,type:str]
        - ENC[AES256_GCM,data:suU7+gNmvKH2Wle+,iv:e5zrIMrHPrHHVVxg4Cnbmj6rWPGHqkLl8m+0xlQdKdU=,tag:WiubeTQabCO74BbSxulM3Q==,type:str]
stash:
    token: ENC[AES256_GCM,data:4gcJrVMAD3dpxwiNRV4bRwTITLeGELyGFpV308RRSq8QuU4tpjzlmXVRnpfbmKJ8va6VgogNTOQbqmHn34z2j6xhexMZqDMc3l9ffu0leu/Zxh7obbY7/PyDorVZgFQ0GO26wFB2lU88sT8uzmdrrxO/titg+n8fmWF12W4z3OrFSIAEUeqb33BQ1sXz0pqe,iv:6hYeyBj4no+vGdKfIXWgu6AyVKTCXU3RDbCvJ6poKRo=,tag:PZ+UrWDdIsujqnR1EVtpbw==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UjQwY1p3REF2RFRoaWM4
            bWJQZnVWNjVHOTB0ZjUzTzhkUjFGRG0rVDN3ClJwWW5jTkx1eGlLL0dRMlliY2dm
            OGdVUkFLZW5kMmdhbUxnWkpRaGhWSlkKLS0tIDJhb2hmWldqQW1ZVVFmcDNJNmw3
            LzM0ZExELzUzMVN1VVowVjBRREtQZWMK7k/CaYtIlHa/46o3dNSKsbgkxyJqfseN
            2+/M/Gr/mPkk7+v3AbkCXSCJXSFomSV3g5iMtBk66+mMVWnMOo5mdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:37:35Z"
    mac: ENC[AES256_GCM,data:Zbx75DhmprQGODmJDetKwsATscRHW00wvnBWLoKP/T4jpq/D6Ry+iGVUyPCRzmgIgFgFmknFdM7qeS0j9lox8NeDUtjGFdyGZktVoS1TWJShogPX6DJJE2Q6olM+GLqFpC3HTGVQAsnS02fX3te8/iWfPLyjOFh2EAP+xGz9C0E=,iv:hMFh0zW241g0BMEyFgssFvOHmHsABy5oE4RL4FMJ2EA=,tag:FPhTXCOT6qi1s57fMpDqrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
